### PR TITLE
Redirect to post when editing a reply

### LINKED ISSUE #315: Edit reply success url should be the parent content
Currently when you edit a reply, after saving the reply loads in a detail view. What should happen is loading of the parent detail view, where the user clicked edit reply.

### PR DESCRIPTION
**Pull request by christophehenry**
Closes #315

### CODE REVIEW

**Comment by jaywink** [comment]
Awesome! A test would be nice for the change?

**Comment by christophehenry** [comment]
NO! I REFUSE TO YIELD TO THE TYRANNY OF THE UNIT TESTS! WHERE IS YOUR FAILTH!?

**Comment by christophehenry** [comment]
Done.

**Comment by christophehenry** [comment]
hacktoberfest

**Review by jaywink — APPROVED** [review]
Awesome, thanks! Congrats on completing Hacktoberfest, with hours to spare! 🎉

**Pull request merged**
